### PR TITLE
[SB-281] Refactor medical question related form

### PR DESCRIPTION
**Pull request by jennyzeng**
# Description

Fix multiple issues related to the form after this PR https://github.com/cmusv-sem/S23SB-SEM-IR/pull/107
for the citizen flow

1. the debouncing should happen when we push update to socket rather than typing or doing selection. otherwise UX may degrade. We just need to cancel the previous call in socket if we get a new update in. 
2. There is an issue that the browser console error keeps saying the formdata becomes uncontrolled. We are using controlled form element, and the value should always reflect our state. use value not default value
3. display if the caller is patient correctly for different roles correctly
4. remove some unnecessary hooks
5. also fixed citizen flow step is not restored properly

# Test Plan

Please explain how this change will be tested.

- [ ] Unit test
- [ ] Integration test (including unit tests with supertest)
- [x] Manual test (Please explain below for the test steps)
- [ ] Not Applicable

check medical data form can still update as expected

# Task Link

Please add related jira task links
https://cmusem.atlassian.net/browse/SB-281

### CODE REVIEW

**Comment by jennyzeng** [comment]
Current dependencies on/for this PR:
* master
  * **PR #110** <a href="https://app.graphite.dev/github/pr/cmusv-sem/S23SB-SEM-IR/110" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/cmusv-sem/S23SB-SEM-IR/110?utm_source=stack-comment).

**Comment by jennyzeng** [comment]
Edit: I may need to update how I do debouncing as it seems the update might be lost since we are doing partial data. I may remove debouncer at all (not super important as we are doing sequential updates via socket anyway)

**Comment by Kaiwen-Bian** [comment]
@jennyzeng I do want to mention that all the forms require auto-save, so any changes users made should be saved automatically without a saving button, one concern I have without a debouncer is that when users change something frequently, we might generate a lot of unnecessary communications(e.g. check and uncheck "Caller is the patient" frequently)

**Review by Yqiyuan — APPROVED** [review]

**Comment by jennyzeng** [comment]
> @jennyzeng I do want to mention that all the forms require auto-save, so any changes users made should be saved automatically without a saving button, one concern I have without a debouncer is that when users change something frequently, we might generate a lot of unnecessary communications(e.g. check and uncheck "Caller is the patient" frequently)

For human interaction speed this is generally ok for real time applications (e.g typing in Google doc and see change reflects on the doc by other users immediately for each character). Plus not many clicks can be performed anyway in 0.5 second time bound you set.

Additionally, I previously used the confirm button to front end validate values such as age before form submission and it is not captured now. Using confirm button also satisfies the previous user story which also mentioned "auto save" requirements

**Comment by Kaiwen-Bian** [comment]
> Using confirm button also satisfies the previous user story which also mentioned "auto save" requirements

I see, then let's put the confirm button back to the form.:)

**Review by bettsongy — APPROVED** [review]

**Comment by jennyzeng** [comment]
> > Using confirm button also satisfies the previous user story which also mentioned "auto save" requirements
> 
> I see, then let's put the confirm button back to the form.:)

yeah I initially also wanted to update the form in real time but found that in that case I would have to handle the invalid input and could be complicated to do the update... I just did it in the submit form style to simplify it. This also technically can be explained as: "once they confirm the change, the system automatically saves it"
We should've talked before implementation to save your time ;)

Also I think you are missing a case that, if user doesn't select an emergency type in the previous step, we will display all kinds of forms in this input information step and allow user to enter them all. If you want to make change to actually happen in real time, then you will also need to update the other two emergency type forms.

**Pull request merged**
